### ISSUE TITLE
Position of DistanceGrabber is not in sync with the respective ControllerAlias on startup

### ISSUE THREAD

**Issue by FireDragonGameStudio** [ExtendRealityLtd/Tilia.Interactions.PointerInteractors.Unity#2]
### Environment

* VR device: Oculus Quest
* Code source: Tilia.Interactions.PointerInteractors.Unity
* Code version: 1.0.0
* Platform version: Unity 2019.3.14f1
* 3rd party dependencies: 
Tilia.Interactions.Interables.Unity
Tilia.CameraRigs.TrackedAlias.Unity
Tilia.Input.UnityInputManager
Tilia.SDK.OculusIntegration.Unity 

### Steps to reproduce

- Set up new project like mentioned at the HowTo sections. TrackedAlias, VelocityTracker, Oculus Integration, InputManager, etc... 
- Setup a new Input.UnityInputManager.1DAxisAction + BooleanAction for grabbing (e.g. TriggerLeft).
- Add an Interactable.
- Add a new Interactor for a ControllerAlias. Hook up the Interactor with the previously created GrabAction and VelocityTracker.
- Add the Interactions.PointerInteractors.DistanceGrabber.
- Set the Interactor setting to the previously created Interactor.

### Expected behavior

The DistanceGrabber should follow along the Interactor to enable pointing via controller movement.

### Current behavior

The DistanceGrabber remains at position 0, 0, 0 when starting the application. After grabbing a Interactable manually it suddenly follows along (not everytime). Can be seen best, when placing an Interactable directly in front of the player. After startup you'll see the pointer at the bottom of the Interactable, but it's not following the controller alias.

### Temporary fix

Hook up the FollowSource setting of Indicators.ObjectPointers.Straight of the DistanceGrabber to manually enable following the ControllerAlias.

Best regards :)

**Comment by thestonefox** [comment]
What object is remaining at the position of 0,0,0?

The DistanceGrabber object will and so will the Pointer object, the object that tracks is the `PointsRenderer` and that tracks every time for me.

**Comment by thestonefox** [comment]
I can't recreate this, maybe someone else can try?

**Comment by FireDragonGameStudio** [comment]
For anyone who wants to test it, I created a GitHub repo -> [https://github.com/FireDragonGameStudio/TiliaDistanceGrabBug](https://github.com/FireDragonGameStudio/TiliaDistanceGrabBug) with my test project and a Youtube Video -> [https://youtu.be/wBL-8bUePfA](https://youtu.be/wBL-8bUePfA) showing the problem.

Sry for beeing so annoying -.-

**Comment by thestonefox** [comment]
I still cant recreate the issue in that repo (I'm using 2019.3.13f1 but i don't see how that would make a difference)

Is it doing it for you in the editor or just at build time?

**Comment by FireDragonGameStudio** [comment]
It works correctly when testing in Editor with UnityXR and SpatialSimulator. It only breaks after deploying to my Quest headset.

**Comment by thestonefox** [comment]
so it is only a problem when built and deployed to the quest then? That's weird.

The code is all doing what it should be doing, the Grabber config passes the Grabber facade interactor to the internal Pointer Follow Source.

This can happen either if the pointer is still disabled or enabled as properties aren't blocked from being set.

The object follower source within the pointer is set by the pointer config and has a "wait for object follower to become enabled" wrapped around the setting of it, so even if the object follower hasn't been enabled at that time then when it becomes enabled it will still run that hook up code. if it is enabled already then the OnAfter code will run and set it up.

I don't see anywhere that a race condition could cause this.

The only potential issue could be that when Unity builds this out that the malimbe code that deals with this on after logic isn't being compiled properly on android for some reason, but that is really clutching at straws.

@bddckr any ideas on what could be causing this?

**Comment by bddckr** [comment]
I don't think Malimbe is at fault here, it would probably blow up with exceptions in that case. (As Malimbe just weaves some IL it either can be run or it can't, but the IL is the same no matter where you deploy to.)

It definitely sounds like there's some indeterministic behavior we're relying on, which is different in Editor vs on Quest. Therefore your idea of a race condition makes sense to me, though that doesn't seem to be it as you just said.

**Comment by FireDragonGameStudio** [comment]
Maybe I can provide further information, when I test this with Oculus Link in Unity Editor. I'll try that asap and let you know.

**Comment by thestonefox** [comment]
The only reason that the object follower source wouldn't be set was if the object follower source observable list wasn't active as we don't allow mutations on inactive components.

But the pointer config uses the wait till enabled code to ensure this can't be the case.

So the only thing that I can think of that could be at fault is that wait till enabled functionality isn't working properly

**Comment by FireDragonGameStudio** [comment]
Short update: Working without problems via Oculus Link.

**Comment by thestonefox** [comment]
I'm going to close this as it's become stale
