### ISSUE TITLE
Distance Grab stops work after force grab to InteractorFacade from a code

### ISSUE THREAD

**Issue by ArtemkaKun** [ExtendRealityLtd/Tilia.Interactions.PointerInteractors.Unity#248]
### Environment

Unity 2022.1.5
Tilia.Interactions.PointerInteractors.Unity - v2.1.16

### Code example

```csharp
// ...

[field: SerializeField]
private InteractorFacade RightHandInteractor { get; set; }
[field: SerializeField]
private InteractorFacade LeftHandInteractor { get; set; }

// ...

private void ReactOnItemWasSelected(int itemID)
{
  // ...
  if (DominantHandValue.Value == HandSide.RIGHT) 
  {
    selectedItem.transform.position = RightHandInteractor.transform.position;
    RightHandInteractor.GrabIgnoreUngrab(selectedItem.gameObject); // Grab() produce the same behavior
  } 
  else 
  {
    selectedItem.transform.position = LeftHandInteractor.transform.position;
    LeftHandInteractor.GrabIgnoreUngrab(selectedItem.gameObject); // Grab() produce the same behavior
  }

  // ...
}
```

### Steps to reproduce

1. Force grab a GameObject to an InteractorFacade with GrabIgnoreUngrab/Grab method from code.
2. Ungrab object (with common ungrab action).
3. Try distance grab object with Interactor you previously force grab to.

### Expected behavior

After grabbing from code and ungrab can distance grab an object with any interactor.

### Current behavior

After grabbing from code and ungrab can grab with distance grab/common grab only by another Interactor, Interactor to which object was grabbed from code - common grab work, distance grab doesn't work.

DistanceGrab -> Surface Data Collision Data Extractor invokes Failed() UnityEvent (img. 1) for that hand that cannot grab with distance grab.

![image1](https://user-images.githubusercontent.com/36485221/174553481-201397a3-0bbb-468c-9ffd-43a7fa2dacd0.png)

**Comment by thestonefox** [comment]
The issue is the `EnablePointer` is staying disabled on ungrab so the pointer interactor is not enabling again. I need to look into why

**Comment by thestonefox** [comment]
Linked issue causing this issue (I think)
https://github.com/ExtendRealityLtd/Tilia.Interactions.Interactables.Unity/issues/128

**Comment by thestonefox** [comment]
Ok try this as a workaround

On your Interactor, select the `Interactor->Internal->InteractionLogic->Interaction.Grabbing` gameobject then in the `GrabInteractorConfigurator` untick the `Touch Before Force Grab` option

I _think_ there's an issue with this, I don't see the purpose for the simulate touch anymore, but if you could try it and see if you notice any errors with it turned off.

**Comment by ArtemkaKun** [comment]
Ok, will do

**Comment by thestonefox** [comment]
I've actually found the issue now, the Touch Before Force Grab is required as it makes sure the events fire in the correct order

`touch before grab`

The issue is, you get a simulated touch, then you get an actual touch, so the interactable thinks its being touched twice, so when you untouch, it thinks it is still touching.

I have a fix in the works for it.

**Comment by thestonefox** [comment]
PR with fix: https://github.com/ExtendRealityLtd/Tilia.Interactions.Interactables.Unity/pull/129
