### ISSUE TITLE
Support for Precision Grab

### ISSUE THREAD

**Issue by SmartCarrion** [ExtendRealityLtd/Tilia.Interactions.PointerInteractors.Unity#36]
## Is your feature request related to a problem?
Yes, Distance grabbing always grabs either the transform center or the attach point of an object.  This isn't good for large or irregularly shaped objects where you want to be able to grab the surface of one end.  Precision grab is built for this scenario, but doesn't work with pointers
## Describe the solution you'd like
If an interactable is set to precision point (or anything really), the object should fly the RayCastHit.Point of the object to the Interactor, then do Grab, and pass the RayCastHit.Point as the grab point to InteractableGrabber (not supported currently that I can tell).
To support this, TransitionToInteractor should by default only apply position change, not rotation change.

## Describe alternatives you've considered
A configuration option on DistanceGrabberFacade could specify whether to 'Grab' to interactable surfaces or just grab the interactable, or this could be chosen based on what type of interactable is being grabbed.
Just adding grab point support to InteractableGrabber would be enough to roll this on our own.

## Additional context
Setting an Offset on TransitionToInteractor as the RayCastHit.Point works to make the object only fly to the surface, but InteracableGrabber still just grabs the transform center.  The offset is easy to store on the DistanceGrabber and set its world position by extracting the RayCastHit.Point.

**Comment by extendreality** [comment]
Resolved in https://github.com/ExtendRealityLtd/Tilia.Interactions.PointerInteractors.Unity/pull/42

**Comment by SmartCarrion** [comment]
Sick!  Will give it a test this weekend!
