### ISSUE TITLE
'Fuzzy' or Cone Grab for small or fast moving objects

### ISSUE THREAD

**Issue by SmartCarrion** [ExtendRealityLtd/Tilia.Interactions.PointerInteractors.Unity#37]
## Is your feature request related to a problem?

When trying to small moving objects at a distance, it is very challenging to aim the pointer and hit grab.  Doing this in a fast and reliable way is effectively impossible.  The distance grabber should be configurable to support a larger grab area if something isn't hit by a single precise raycast.

## Describe the solution you'd like

Using a configurable [cone cast](https://github.com/walterellisfun/ConeCast)  or sphere cast, find the closest valid item that is hit, and highlight the best grab point on it (easy to do closest point, or better yet, the surface point closest to center of cone, or the orientation handle if there is one active)

## Describe alternatives you've considered
Putting huge grab colliders on the interactors then flying grabbed objects to the interactor.

## Additional context

Attached my current draft of ConeCast based on StraightLineCast.
[ConeCastTilia.txt](https://github.com/ExtendRealityLtd/Tilia.Interactions.PointerInteractors.Unity/files/5030754/ConeCastTilia.txt)

**Comment by SmartCarrion** [comment]
I've made some improvements based on another [casting git](https://github.com/ALee1303/Sphere-Raycasting) to help with item selection.  Now it chooses the item closest item by distance if it is within a tight angle, or the closest item by angle in a larger cone if there is nothing within the tight cone.  This way it feels more selective about choosing the thing you mean to be pointing at, while still giving you a broad possible hit area.    

I also started raycasting to the object after the cone cast, to detect if the item is blocked by a different world object.  This isn't quite working for me yet though, my raycasts are still penetrating everything in my test scene.
[ConeCastTilia2.cs.txt](https://github.com/ExtendRealityLtd/Tilia.Interactions.PointerInteractors.Unity/files/5078401/ConeCastTilia2.cs.txt)
(I know this should be a branch and pull request, I need to figure that out)

The selected spot tends to pop around between close items with natural hand shake.  We could add something like the Interactor's configurable 'Precognition' so that it stays attached to an object and doesn't pop around as much.

**Comment by thestonefox** [comment]
Also take a look at https://github.com/walterellisfun/ConeCast

**Comment by SmartCarrion** [comment]
Yup, I linked that too because you’d told me about it previously. That’s what I started with.

**Comment by thestonefox** [comment]
This would benefit from https://github.com/ExtendRealityLtd/Zinnia.Unity/issues/538

**Comment by thestonefox** [comment]
You can now use the cast converters to achieve this. You'd need to write a cast converter that converted to the conecast then anywhere that uses a raycast would be converted to using a conecast
