### ISSUE TITLE
Distance grab can interfere with local grab

### ISSUE THREAD

**Issue by SmartCarrion** [ExtendRealityLtd/Tilia.Interactions.PointerInteractors.Unity#55]
# Environment

* Code source:  PointerInteractor
* Code version: 1.3.8
* Platform version: Unity 2019.4.10
* 3rd party dependencies: none

### Steps to reproduce

Setup pointerinteractor, and a sphere collider grab interactor, initiated on the same button. 
Create two interactables near each other.
Stick your hand into one object, and point the pointer at the distant object. Initiate grab.

### Expected behavior
When pulling the grab button, it should grab the closest object you have your hand on, or if there is no close object, grab the distant object you are pointing at.

### Current behavior
The distance grabber will override the local grab, the distant object pulls in close, and then you probably pick up the close object.

**Comment by SmartCarrion** [comment]
A decent fix is to turn off just the Pointer game object if the Interactor is IsTouching or IsGrabbing.  If you turn off the whole distance grabber game object, then some timing issues/race conditions can cause you to miss the actual grab after distance grabbing.

**Comment by SmartCarrion** [comment]
Sorry, I did but removed the headings and compressed redundancy.  I will resubmit

**Comment by thestonefox** [comment]
resolved with https://github.com/ExtendRealityLtd/Tilia.Interactions.PointerInteractors.Unity/pull/81
