### ISSUE TITLE
Distance Grab needs configurable FollowSource

### ISSUE THREAD

**Issue by SmartCarrion** [ExtendRealityLtd/Tilia.Interactions.PointerInteractors.Unity#60]
The distance grab is currently forced to emit from the attached interactor.  If the hand model or thing that is doing the grabbing does not align with the interactor setup, it is emitting from the wrong direction.  

Similar to the teleporter, the distance grabber needs a configurable FollowSource.

In DistanceGrabberConfigurator.cs:
        public virtual void ConfigureInteractor()
        {
            Pointer.FollowSource = Facade.Interactor.gameObject;

**Comment by thestonefox** [comment]
You need to follow the issue template when raising an issue otherwise the ticket gets closed
